version: '2.0.1+{build}'

image:
  - macos-sonoma
  - Ubuntu2204
  - Visual Studio 2022

configuration: Release

branches:
  except:
    - gh-pages

install:
  - ps: echo "$(git describe --tags --dirty --broken)+$env:APPVEYOR_BUILD_NUMBER"

for:
  -
    matrix:
      only:
        - image: macos-sonoma
    before_build:
      - uname -a
      - cmake --version
      - clang++ --version
    build_script:
      - cmake -B build -DCMAKE_PREFIX_PATH=${HOME}/Qt/6.6/macos -DCMAKE_INSTALL_PREFIX=`pwd`/local -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DPACKAGE_SYSTEM_DISTRIBUTION=osx-sonoma
      - cmake --build build
      - (cd build ; cpack --verbose -G DragNDrop)
    artifacts:
      - path: build/vhf-sim-*.dmg

  -
    matrix:
      only:
        - image: Visual Studio 2022
    environment:
      QTHOME: C:\Qt\6.7\mingw_64
      QT_TOOLS_PATH: C:\Qt\Tools\mingw810_32\bin
      GENERATOR: "MinGW Makefiles"
    before_build:
      - cmd: set PATH=%QT_TOOLS_PATH%;%PATH%
    build_script:
      - cmd: cmake -B build -G "%GENERATOR%" -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin" -DCMAKE_BUILD_TYPE=%CONFIGURATION% C:\projects\vhf-sim
      - cmd: cmake --build build --config %CONFIGURATION%
      - cmd: cd build
      - cmd: cpack -G NSIS
    artifacts:
      - path: build\vhf-sim-*.exe

  -
    matrix:
      only:
        - image: Ubuntu2204
    before_build:
      - sh: sudo apt-get update
      - sh: sudo apt-get install -qq qt6-base-dev qt6-multimedia-dev qt6-base-dev-tools qt6-tools-dev-tools
    build_script:
      - sh: cmake -B build -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DPACKAGE_SYSTEM_DISTRIBUTION=ubuntu2004
      - sh: cmake --build build
      - sh: (cd build ; cpack -G DEB)
    artifacts:
      - path: build/vhf-sim-*.deb

